### ISSUE TITLE
阅读你们源码，看到一个问题

### ISSUE THREAD

**Issue by bingowang1991** [sensorsdata/sa-sdk-android#106]
看到可视化上报截屏时，这里上传了一个view_path
jsonSnapObject.put("element_path", viewNode.getViewPath());

但是该取值与点击view时，采集的$view_path不对应，我理解，这样的话，可视化埋点后，通过view_path是无法匹配到这个view的

麻烦帮忙解答下，谢谢

**Comment by wp3355168** [comment]
截屏时候的 element_path 只是当前的自身的一个路径，前端在计算的时候会从截屏的根节点到当前节点的 element_path 拼接，这样拼接出来的完整的路径就同点击的时候的路径是一样的。

**Comment by wp3355168** [comment]
> 看到可视化上报截屏时，这里上传了一个view_path jsonSnapObject.put("element_path", viewNode.getViewPath());
> 
> 但是该取值与点击view时，采集的$view_path不对应，我理解，这样的话，可视化埋点后，通过view_path是无法匹配到这个view的
> 
> 麻烦帮忙解答下，谢谢


截屏时候的 element_path 只是当前的自身的一个路径，前端在计算的时候会从截屏的根节点到当前节点的 element_path 拼接，这样拼接出来的完整的路径就同点击的时候的路径是一样的。

**Comment by bingowang1991** [comment]
那这里觉得可以优化下，你们截屏的时候，还上传了view_selector，如果有了element_path，那这个view_selector是不是可以去掉？去掉后，可以减少流量消耗

**Comment by wp3355168** [comment]
嗯，view_selector 暂时可以去掉。

**Comment by wp3355168** [comment]
> 

嗯，view_selector 暂时可以去掉
