### ISSUE TITLE
SensorsDataContentProvider自动初始化导致隐私合规不通过

### ISSUE THREAD

**Issue by shijianan201** [sensorsdata/sa-sdk-android#107]
我们公司的APP被通信局查出来存在提前搜集用户信息的问题，调试后发现神策埋点sdk存在通过SensorsDataContentProvider提前初始化的问题，希望能单独提供方法进行初始化。类完整路径（com.sensorsdata.analytics.android.sdk.data.SensorsDataContentProvider）

**Comment by shijianan201** [comment]
> 有对应的扫描信息吗？SensorsDataContentProvider 这里我们只做了一些对象初始化，没有涉及到数据采集

神策的确没有提前获取信息，但是能不能让我们开发者控制该什么时候初始化sdk呢？

**Comment by dengshiwei** [comment]
ContentProvider 是在 AndroidManifest.xml 中注册，由系统进行加载。这块目前无法控制，SDK 的初始化方法是可以由开发者控制的。

**Comment by dengshiwei** [comment]
@shijianan201 你们最近检测通过了吗？是否有更详细的检测说明。

**Comment by shijianan201** [comment]
> 

sdk版本升级了6.4.2，上次华为应用市场上去了，现在又被拒了，提示信息如下

您的应用频繁获取用户信息：ANDROID ID 4次/分钟; 应用内集成的[SensorsAnalytics、神策]SDK频繁获取用户信息：ANDROID ID 4次/分钟，且未在隐私政策中进行说明，不符合华为应用市场审核标准，为不影响用户体验，请您尽快完成整改。
­整改建议：请勿频繁收集用户的个人信息，并在隐私政策中对应用所获取的个人信息的目的和频率进行说明。

**Comment by dengshiwei** [comment]
@shijianan201 华为市场我们自己也送检过，没有遇到提示说「ANDROID ID 4次/分钟」，更关键的应该是「且未在隐私政策中进行说明，不符合华为应用市场审核标准」，这块你们有集成我们的隐私说明吗？这块你可以找我们对应的技术支持同学协助你。

**Comment by shijianan201** [comment]
> 

已经集成了你们的隐私说明

**Comment by dengshiwei** [comment]
@shijianan201 这个你看是否能咨询一下华为的客服了解一下详情吧，我们读取 Android_ID 的接口值都是会缓存的。

**Comment by shijianan201** [comment]
> @shijianan201 这个你看是否能咨询一下华为的客服了解一下详情吧，我们读取 Android_ID 的接口值都是会缓存的。

有方法禁止sdk获取AndroidID么？

**Comment by dengshiwei** [comment]
@shijianan201 在对应的项目 build.gradle 中配置。
```groovy
sensorsAnalytics {
     sdk {
          disableAndroidID = true
     }
}
```

**Comment by shijianan201** [comment]
> @shijianan201 在对应的项目 build.gradle 中配置。
> 
> ```groovy
> sensorsAnalytics {
>      sdk {
>           disableAndroidID = true
>      }
> }
> ```

SDK里getAndroidId那个方法能改一下名字么，最好不要有AndroidID字样，华为检测时应该是根据函数名字去计算的频率，下面是华为给的堆栈信息。

尊敬的开发者，您好！您的应用频繁获取用户信息：应用内集成的[SensorsAnalytics、神策]SDK频繁获取用户信息：ANDROID ID 4次/分钟，请勿频繁收集用户的个人信息，并在隐私政策中对应用所获取的个人信息的目的和频率进行说明，感谢您的支持！

应用内集成的[SensorsAnalytics、神策]SDK频繁获取用户信息：ANDROID ID
[com.sensorsdata.analytics.android.sdk.util.SensorsDataUtils.getAndroidID(SensorsDataUtils.java:2),
 com.sensorsdata.analytics.android.sdk.util.SAContextManager.getAndroidId(SAContextManager.java:2),
 com.sensorsdata.analytics.android.sdk.useridentity.UserIdentityAPI.<init>(UserIdentityAPI.java:8),
 com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI.<init>(AbstractSensorsDataAPI.java:37),
 com.sensorsdata.analytics.android.sdk.SensorsDataAPI.<init>(SensorsDataAPI.java:2),
 com.sensorsdata.analytics.android.sdk.SensorsDataAPI.getInstance(SensorsDataAPI.java:5),
 com.sensorsdata.analytics.android.sdk.SensorsDataAPI.startWithConfigOptions(SensorsDataAPI.java:1),

**Comment by dengshiwei** [comment]
@shijianan201 这个后续我们考虑一下吧

**Comment by dengshiwei** [comment]
@shijianan201 v6.5.0 版本已经修改名称。同时我们内部上架华为能够正常上架，没有提示获取次数的问题。

**Comment by shijianan201** [comment]
> @shijianan201 v6.5.0 版本已经修改名称。同时我们内部上架华为能够正常上架，没有提示获取次数的问题。

好的，我们这边也没出现这个问题了

**Comment by wenboLee** [comment]
> @shijianan201 在对应的项目 build.gradle 中配置。
> 
> ```groovy
> sensorsAnalytics {
>      sdk {
>           disableAndroidID = true
>      }
> }
> ```

@dengshiwei  我们集成的是 flutter 版的，小米商店也遇到同样的问题。
原生版本用的是  
api 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:6.6.0'，

在android 模块里面、外面添加配置，都会报错，是还需要安装什么插件吗？
```
android {
    compileSdkVersion 33

}
```

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method sensorsAnalytics() for arguments [build_bancf21ke5q4nvfnig5sd3pm2$_run_closure3@17809931] on project ':app' of type org.gradle.api.Project.
```

**Comment by wenboLee** [comment]
ok，我找到原因了，需要把 project 的 android 插件配置，而flutter版插件没有~
