### ISSUE TITLE
SensorsAnalyticsSDK: 6.5.1 Build failed

### ISSUE THREAD

**Issue by xyz-fly** [sensorsdata/sa-sdk-android#112]
androidgradle: 7.3.0
gradle: 7.5.1
SensorsAnalyticsSDK: 6.5.1
android-gradle-plugin2: 3.5.0

build app failure

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field 'transform' from type 'com.android.build.gradle.internal.pipeline.IncrementalTransformTask': error writing value of type 'com.sensorsdata.analytics.android.plugin.SensorsAnalyticsTransform'
> Configuration cache state could not be cached: field 'transformHelper' from type 'com.sensorsdata.analytics.android.plugin.SensorsAnalyticsTransform': error writing value of type 'com.sensorsdata.analytics.android.plugin.SensorsAnalyticsTransformHelper'
   > Configuration cache state could not be cached: field 'android' from type 'com.sensorsdata.analytics.android.plugin.SensorsAnalyticsTransformHelper': error writing value of type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension'
      > Configuration cache state could not be cached: field 'composeOptions' from type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension': error writing value of type 'com.android.build.gradle.internal.dsl.ComposeOptionsImpl'
         > Configuration cache state could not be cached: field 'dslServices' from type 'com.android.build.gradle.internal.dsl.ComposeOptionsImpl': error writing value of type 'com.android.build.gradle.internal.services.DslServicesImpl'
            > Configuration cache state could not be cached: field 'versionedSdkLoaderServiceProvider' from type 'com.android.build.gradle.internal.services.DslServicesImpl': error writing value of type 'com.android.build.gradle.internal.plugins.BasePlugin$dslServices$2$1'
               > Configuration cache state could not be cached: field 'this$0' from type 'com.android.build.gradle.internal.plugins.BasePlugin$dslServices$2$1': error writing value of type 'com.android.build.gradle.internal.plugins.AppPlugin'
                  > Configuration cache state could not be cached: field 'androidComponentsExtension$delegate' from type 'com.android.build.gradle.internal.plugins.AppPlugin': error writing value of type 'kotlin.SynchronizedLazyImpl'
                     > Configuration cache state could not be cached: field 'value' from type 'kotlin.InitializedLazyImpl': error writing value of type 'com.android.build.gradle.internal.plugins.AppPlugin$ApplicationAndroidComponentsExtensionImplCompat'
                        > Configuration cache state could not be cached: field 'variantApiOperations' from type 'com.android.build.gradle.internal.plugins.AppPlugin$ApplicationAndroidComponentsExtensionImplCompat': error writing value of type 'com.android.build.api.extension.impl.VariantApiOperationsRegistrar'
                           > Configuration cache state could not be cached: field 'extension' from type 'com.android.build.api.extension.impl.VariantApiOperationsRegistrar': error writing value of type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated'
                              > Configuration cache state could not be cached: field 'buildTypes' from type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
                                 > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
                                    > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithManyActions'
                                       > Configuration cache state could not be cached: field 'multipleActions' from type 'org.gradle.internal.ImmutableActionSet$SetWithManyActions': error writing value of type 'com.google.common.collect.RegularImmutableSet'
                                          > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
                                             > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3'
                                                > Configuration cache state could not be cached: field '$tmp0' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager$3': error writing value of type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager'
                                                   > Configuration cache state could not be cached: field 'sourceSetManager' from type 'com.android.build.gradle.internal.variant.LegacyVariantInputManager': error writing value of type 'com.android.build.gradle.internal.dependency.SourceSetManager'
                                                      > Configuration cache state could not be cached: field 'sourceSetsContainer' from type 'com.android.build.gradle.internal.dependency.SourceSetManager': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
                                                         > Configuration cache state could not be cached: field 'eventRegister' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister'
                                                            > Configuration cache state could not be cached: field 'addActions' from type 'org.gradle.api.internal.collections.DefaultCollectionEventRegister': error writing value of type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions'
                                                               > Configuration cache state could not be cached: field 'actions' from type 'org.gradle.internal.ImmutableActionSet$SetWithFewActions': error writing value of type '[Lorg.gradle.api.Action;'
                                                                  > Configuration cache state could not be cached: field 'delegate' from type 'org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction': error writing value of type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1'
                                                                     > Configuration cache state could not be cached: field 'val$action' from type 'org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1'
                                                                        > Configuration cache state could not be cached: field '$target' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt$syncKotlinAndAndroidSourceSets$1': error writing value of type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget'
                                                                           > Configuration cache state could not be cached: field 'compilations' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget': error writing value of type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer'
                                                                              > Configuration cache state could not be cached: field 'index' from type 'org.gradle.api.internal.FactoryNamedDomainObjectContainer': error writing value of type 'org.gradle.api.internal.DefaultNamedDomainObjectCollection$UnfilteredIndex'
                                                                                 > Configuration cache state could not be cached: field 'map' from type 'org.gradle.api.internal.DefaultNamedDomainObjectCollection$UnfilteredIndex': error writing value of type 'java.util.TreeMap'
                                                                                    > Configuration cache state could not be cached: field 'androidVariant' from type 'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation': error writing value of type 'com.android.build.gradle.internal.api.ApplicationVariantImpl'
                                                                                       > Configuration cache state could not be cached: field 'testVariant' from type 'com.android.build.gradle.internal.api.ApplicationVariantImpl': error writing value of type 'com.android.build.gradle.internal.api.TestVariantImpl'
                                                                                          > Configuration cache state could not be cached: field 'variantData' from type 'com.android.build.gradle.internal.api.TestVariantImpl': error writing value of type 'com.android.build.gradle.internal.variant.TestVariantData'
                                                                                             > Configuration cache state could not be cached: field 'testedVariantData' from type 'com.android.build.gradle.internal.variant.TestVariantData': error writing value of type 'com.android.build.gradle.internal.variant.ApplicationVariantData'
                                                                                                > Configuration cache state could not be cached: field 'artifacts' from type 'com.android.build.gradle.internal.variant.ApplicationVariantData': error writing value of type 'com.android.build.api.artifact.impl.ArtifactsImpl'
                                                                                                   > Configuration cache state could not be cached: field 'storageProvider' from type 'com.android.build.api.artifact.impl.ArtifactsImpl': error writing value of type 'com.android.build.api.artifact.impl.StorageProviderImpl'
                                                                                                      > Configuration cache state could not be cached: field 'directory' from type 'com.android.build.api.artifact.impl.StorageProviderImpl': error writing value of type 'com.android.build.api.artifact.impl.TypedStorageProvider'
                                                                                                         > Configuration cache state could not be cached: field 'singleStorage' from type 'com.android.build.api.artifact.impl.TypedStorageProvider': error writing value of type 'java.util.LinkedHashMap'
                                                                                                            > java.util.ConcurrentModificationException (no error message)

**Comment by dengshiwei** [comment]
@xyz-fly 可以参照一下这篇帖子的处理：https://stackoverflow.com/questions/71793217/gradle-configuration-cache-state-could-not-be-cached，清除缓存重新编译试试

**Comment by xyz-fly** [comment]
可以了
