### ISSUE TITLE
监听App启动与退出

### ISSUE THREAD

**Issue by ATMLGG** [sensorsdata/sa-sdk-android#118]
虚心请教下，为何在全埋点方案中监听应用启动与退出时，采用监听Activity数量的方案，而不直接使用Application的onCreate，这个回调多进程下的确会走多次，但也可以判断进程名来决定是否上报，是出于什么考虑呢

**Comment by dengshiwei** [comment]
目前开发者在调用 SDK 初始化时存在不确定性，不一定在 Application 的 onCreate 方法中调用，监听比较困难。另一个就是退出没法监听，系统没有对应的 Application 生命周期监听。

**Comment by ATMLGG** [comment]
的确，感觉自己有点钻牛角尖了，十分感谢
