### ISSUE TITLE
移除部分不需要的引用库时发生异常

### ISSUE THREAD

**Issue by xyz-fly** [sensorsdata/sa-sdk-android#119]
我使用了神策sdk6.6.2版本，在app的gradle文件中，按照官方说明，移除了5个不需要的插件，配置内容如下：
    implementation(libs.sensorsdata) {
        exclude(group = libs.sensorsdata.asProvider().get().group, module = "advert") // 广告模块
        exclude(group = libs.sensorsdata.asProvider().get().group, module = "encrypt") // 加密模块
        exclude(group = libs.sensorsdata.asProvider().get().group, module = "exposure") // 曝光模块
        exclude(group = libs.sensorsdata.asProvider().get().group, module = "push") // 推送模块
        exclude(group = libs.sensorsdata.asProvider().get().group, module = "visual") // 可视化模块
    }

libs.versions.xml的文件中对神策库描述如下：
sensorsdata = { group = "com.sensorsdata.analytics.android", name = "SensorsAnalyticsSDK", version = "6.6.2" }

运行启动后，调用SensorsDataAPI的track方法（public void track(final String eventName, JSONObject properties)）时报错内容如下：
com.sensorsdata.analytics.android.sdk.core.mediator.protocol.SAModuleProtocol: Provider com.sensorsdata.analytics.android.sdk.push.core.PushProtocolImp not found

**Comment by HSL5430** [comment]
![image](https://user-images.githubusercontent.com/17978969/215237394-cdcc561a-c330-4ebd-96a8-76b530fbbc4c.png)
遇到了同样的问题，这个版本新增了这个文件导致的，需要他们看下怎么解决吧

**Comment by dengshiwei** [comment]
@xyz-fly @HSL5430 问题已收到，近期会进行修复。

**Comment by dengshiwei** [comment]
@xyz-fly @HSL5430 当前阶段建议你们这样按需集成，别使用 exclude。
```java
implementation 'com.sensorsdata.analytics.android:core:0.1.5'
implementation 'com.sensorsdata.analytics.android:autoTrack:0.1.5'
 implementation 'com.sensorsdata.analytics.android:visual:0.1.5'
implementation 'com.sensorsdata.analytics.android:push:0.1.5'
implementation 'com.sensorsdata.analytics.android:exposure:0.1.5'
implementation 'com.sensorsdata.analytics.android:encrypt:0.1.5'
implementation 'com.sensorsdata.analytics.android:advert:0.1.5'
```

**Comment by dengshiwei** [comment]
@xyz-fly @HSL5430 v6.6.3 版本已经修复该问题
