### ISSUE TITLE
android-plugin升级到1.2.0后报Failed to resolve: com.sensorsdata.analytics.android:SensorsAnalyticsSDK-Runtime:1.0.2

### ISSUE THREAD

**Issue by fengruisd** [sensorsdata/sa-sdk-android#12]

**Comment by wangzhzh** [comment]
//添加 Sensors Analytics maven 库地址
        maven {
            url 'https://dl.bintray.com/zouyuhan/maven'
        }

**Comment by wangzhzh** [comment]
问题解决了吗？

**Comment by fengruisd** [comment]
你好，解决了，谢谢。只是为什么不发布到jcenter上呢

**Comment by wangzhzh** [comment]
发布了，只是jcenter新的地址变了，而Android studio默认不在这个地址里搜索
