### ISSUE TITLE
androidstudio升级后，gradle最低版本8.0，gradle部分API被移出，编译后直接报错

### ISSUE THREAD

**Issue by xyz-fly** [sensorsdata/sa-sdk-android#123]
androidstudio升级后，gradle最低版本8.0，gradle部分API被移出，编译后直接报错

> Failed to apply plugin 'com.sensorsdata.analytics.android'.
   > API 'android.registerTransform' is removed.

引自：[](https://developer.android.com/studio/releases/gradle-plugin-api-updates?hl=zh-cn#transform-removed)

AGP 8.0
以下是 AGP 8.0 的重要 API 更新。

移除了 Transform API
从 AGP 8.0 开始，[Transform](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/transform/Transform?hl=zh-cn) API 将被移除。这意味着，软件包 com.android.build.api.transform 中的所有类都会被移除。

Transform API 即将被移除，以提高 build 的性能。使用 Transform API 的项目会强制 AGP 对 build 使用优化程度不够的流程，从而导致构建时间大幅增加。同时也很难使用 Transform API 以及将其与其他 Gradle 功能结合使用；这些替代 API 可让您更轻松地扩展 AGP，而不会引起性能问题或 build 正确性问题。

替代 API
Transform API 没有单一的替代 API，每个用例都会有新的针对性 API。所有替代 API 都位于 androidComponents {} 代码块中，在 AGP 7.2 中均有提供

**Comment by GvcZhang** [comment]
已在测试中，近期会发布版本，尽情关注。

**Comment by liuweiqiang2016** [comment]
Android Plugin v4.0.0-beta 已发布，支持 AGP 8.0+，详细信息见：https://github.com/sensorsdata/sa-sdk-android-plugin2/releases/tag/v4.0.0-beta
