### ISSUE TITLE
神策只能通过gradle 添加依赖的方式使用sdk吗?

### ISSUE THREAD

**Issue by shenahobo** [sensorsdata/sa-sdk-android#13]
能否使用jar包 或者其他的方式吗?

**Comment by wangzhzh** [comment]
因为我们代码里定义了一些 id，所以暂不支持 jar 包的方式，可以使用源码的方式集成。

**Comment by shenahobo** [comment]
就像你们demo中一样直接,
compile project(':SensorsAnalyticsSDK')?
这样都功能没有影响是把?

**Comment by wangzhzh** [comment]
你是我们的客户吗？
还是自己学习？
