### ISSUE TITLE
小部分用户数据不准

### ISSUE THREAD

**Issue by farker** [sensorsdata/sa-sdk-android#14]
使用神策发现有小部分用户一天有几十万甚至上百万条数据。实际上用户每天的数据是几百几千条。我们使用其他工具和自家接口埋点数据都正常。只有神策有这个问题。

**Comment by Zuoweixiang** [comment]
您好，方便的话联系下我们的微信号 SensorsData_iOS 我们的技术支持同学会和您沟通下这个问题。
