### ISSUE TITLE
复制数据接收地址

### ISSUE THREAD

**Issue by xfmax** [sensorsdata/sa-sdk-android#17]
复制完都是这个：http://gamedemo.cloud.sensorsdata.cn:8006/sa?project=default&token=******，但是使用这个，传不上去数据啊？而且这个token怎么获取，文档中都没看见啊？project应该是什么？都没有啊？

**Comment by lixiang9** [comment]
为啥要向神策的 demo 环境发数据呢？ 你想要试用的话，可以联系商务给你开通一个你自己的环境来进行数据的发送。

**Comment by lixiang9** [comment]
神策的 demo 作为展示的用途，是不允许有数据导入的。
project 不写默认指定测试项目， token 为 * 代表你账号的权限不够，只有 admin 和 管理员权限的账号才可以复制正确的地址。
如果你已经是神策的某个客户，那么可以在沟通群提问。如果只是想测试一下神策，那么可以在官网预约顾问演示，让商务给你创建一个自己的环境进行测试。
