### ISSUE TITLE
fragment自动埋点对library不生效？

### ISSUE THREAD

**Issue by fengruisd** [sensorsdata/sa-sdk-android#18]
我的应用包含多个library，library里包含fragment，测试发现application里的fragment是可以自动埋点的，但是library里的不行。编译过程有如下打印，lib*-xxx都是我的library。
...
excludeJar:::/Users/lib1-xxxx/build/intermediates/intermediate-jars/debug/classes.jar
excludeJar:::/Users/lib2-xxxx/build/intermediates/intermediate-jars/debug/classes.jar
excludeJar:::/Users/lib3-xxxx/build/intermediates/intermediate-jars/debug/classes.jar
...

所以想问一下：
1、自动埋点是否支持library里的fragment
2、支持的话应该如何配置？AspectjExtension里有includeJarFilter和excludeJarFilter，是配置这个吗？

**Comment by fengruisd** [comment]
通过在app的build.gradle中添加下面的配置解决了
sensorsAnalytics {
    includeJarFilter = ["lib*-"]
}
请问是否有更好的解决方法？我在官方文档中没有找到说明，另外是否有微信或者QQ群，可以在遇到问题时及时请教

**Comment by V-zhangyunxiang** [comment]
目前只能通过你说的方式采集库模块的 Fragment 浏览事件，我们交流群只面向客户，不对个人，感谢你的关注。

**Comment by fengruisd** [comment]
我也是客户啊。。。公司在用神策埋点，不过我个人是从去年刚刚接手
