### ISSUE TITLE
集成Android SDK后提示'compile' is obsolete

### ISSUE THREAD

**Issue by zhangliangnbu** [sensorsdata/sa-sdk-android#22]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
不清楚是神策sdk还是插件引起，希望解决下
我的配置环境如下：

1. Android Studio 3.1.3
2. android_gradle_plugin 3.1.3
3. 神策skd版本 1.10.6
2. 神策gradle-plugin2:1.0.3

**Comment by dengshiwei** [comment]
@zhangliangnbu 这是由于 gradle 版本低导致的，你可以升级下最新的插件试试。

**Comment by zhangliangnbu** [comment]
升级神策插件后，问题解决了。
你们应该更新下文档了，因为文档里还是写了`1.0.2`

**Comment by wangzhzh** [comment]
好的，我们稍后就更新

**Comment by wangzhzh** [comment]
已经更新
