### ISSUE TITLE
自动跟踪点击事件不起作用

### ISSUE THREAD

**Issue by xiaoyurenzhaoxin** [sensorsdata/sa-sdk-android#23]
eventTypeList.add(SensorsDataAPI.AutoTrackEventType.APP_CLICK);
        SensorsDataAPI.sharedInstance().enableAutoTrack(eventTypeList);

我在ACTIVITY里写了个BUTTON，点击时候不能自动发出点击跟踪信息，其他的APP_VIEW_SCREEN等可以

**Comment by dengshiwei** [comment]
这个项目只是 SDK部分，你需要添加插件才能自动采集 $AppClick 事件，具体的配置可以参见 readme 文件。

**Comment by wangzhzh** [comment]
请问，你的问题解决了吗？

**Comment by wangzhzh** [comment]
请问，你的问题解决了吗？

**Comment by lipeng219901** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
        **classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:1.0.2'**

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

@dengshiwei  编译的jar 里面怎么实使用呢

**Comment by wangzhzh** [comment]
https://sensorsdata.cn/manual/android_sdk.html

**Comment by wangzhzh** [comment]
使用 ASM 处理 .class 文件
