### ISSUE TITLE
统计数据在哪看呢

### ISSUE THREAD

**Issue by keyescgm** [sensorsdata/sa-sdk-android#24]
统计的埋点数据在哪看呢？

**Comment by wangzhzh** [comment]
请问你是个人还是我们神策的客户？

**Comment by keyescgm** [comment]
个人，接入神策用来学习埋点行为 以及  查看最后埋点结果（期待带报表的那种）

**Comment by wangzhzh** [comment]
需要你在我们官网申请demo，然后将数据接入地址填写为demo 的数据接入地址。

**Comment by keyescgm** [comment]
在哪申请呢？我看官网上只有几个体验的Demo...

**Comment by wangzhzh** [comment]
就是那个

**Comment by keyescgm** [comment]
没找到demo 的数据接入地址。

**Comment by keyescgm** [comment]
就是说这个无法获取?
![image](https://user-images.githubusercontent.com/9543572/44971156-173b2d00-af87-11e8-8c94-c54e7b64729b.png)
这个地址是测试用的?
![image](https://user-images.githubusercontent.com/9543572/44971167-2326ef00-af87-11e8-9f27-35bc5f734660.png)

那我怎么我看的数据呢?

**Comment by wangzhzh** [comment]
个人无法通过神策分析查看数据，只能通过 log 查看触发的事件
