### ISSUE TITLE
公共属性没有加入到trackCustom事件中

### ISSUE THREAD

**Issue by liuxing1992** [sensorsdata/sa-sdk-android#26]

**Comment by wangzhzh** [comment]
可以详细描述一下吗？

**Comment by liuxing1992** [comment]
我用的是2.0.0 版sdk 我在registerSuperProperties自定义了一个Global_Data的上报event 然后在其他track上报时 公共属性没上报
代码如下：
  public void registerSuperProperties(JSONObject superProperties) {
        try {
            if (superProperties == null) {
                return;
            }

            PersistentSuperProperties var2 = this.mSuperProperties;
            synchronized(this.mSuperProperties) {
                JSONObject properties = (JSONObject)this.mSuperProperties.get();
                SensorsDataUtils.mergeJSONObject(superProperties, properties);
                this.mSuperProperties.commit(properties);
                if (this.mDebugMode != SensorsDataAPI.DebugMode.DEBUG_OFF) {
                    SALog.d("SA.SensorsDataAPI", "mSuperProperties" + this.mSuperProperties.toString());
                }
            }

            this.trackEvent(EventType.TRACK_CUSTOM, "Global_Data", superProperties, (String)null);
        } catch (Exception var6) {
            var6.printStackTrace();
        }

    }

**Comment by wangzhzh** [comment]
你这个自定义的逻辑比较多，是否可以给我们做一个可以复现问题的demo？我们来排查一下。
