### ISSUE TITLE
3.0无法编译

### ISSUE THREAD

**Issue by huaminghui** [sensorsdata/sa-sdk-android#28]
3.0无法编译

**Comment by wangzhzh** [comment]
具体问题是什么？

**Comment by wangzhzh** [comment]
你好，你目前碰到的具体问题是什么？

**Comment by renqingyou** [comment]
@huaminghui ，可以扫二维码加我们的sdk讨论群 

![](https://github.com/sensorsdata/sa-sdk-android/blob/master/screenshots/qrCode.jpeg)

**Comment by renqingyou** [comment]
@huaminghui 
![image](https://user-images.githubusercontent.com/13671610/52707114-ecd3ae00-2fc1-11e9-8c7e-afc32e85e058.png)

**Comment by wangzhzh** [comment]
你的问题解决了吗？

**Comment by wangzhzh** [comment]
close
