### ISSUE TITLE
异步初始化

### ISSUE THREAD

**Issue by zengcanxiang** [sensorsdata/sa-sdk-android#29]
我们打算在异步线程中初始化神策。 

在`SensorsDataActivityLifecycleCallbacks`类中报错crash。

`SensorsDataActivityLifecycleCallbacks`的构造函数中`new Handler()` 是没有传入`Looper.getMainLooper()`对象。

暂时只发现了这个

**Comment by dengshiwei** [comment]
@zengcanxiang tks

**Comment by wangzhzh** [comment]
已 Fix
