### ISSUE TITLE
android gradle plugin 3.3.1 apaptive

### ISSUE THREAD

**Issue by wengqizun** [sensorsdata/sa-sdk-android#30]
实在不知道你们的gradle plugin去哪里反馈，所以只能在sdk这里反馈问题了。
我更新android studio 到3.3.1，同步更新了android gradle plugin 3.3.1 ，构建应用后报错：
`WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.`
看日志是你们的插件使用了过时的api，麻烦适配一下更新一下插件版本。

**Comment by renqingyou** [comment]
@wengqizun 新年好！我们的插件地址是https://github.com/sensorsdata/sa-sdk-android-plugin2,你现在使用的插件版本和SDK版本号分别是多少呢？

**Comment by wengqizun** [comment]
> @wengqizun 新年好！我们的插件地址是https://github.com/sensorsdata/sa-sdk-android-plugin2
> ,你现在使用的插件版本和SDK版本号分别是多少呢？

close吧，我更新到你们最新版本的插件就好了。
