### ISSUE TITLE
埋点上报的数据问题

### ISSUE THREAD

**Issue by martin-huang** [sensorsdata/sa-sdk-android#31]
可以问下为什么你们的上报是乱序的，是否可以改为配置 按照时间的先进先出的 上报体系，顺便可以问下一个小白问题嘛 为什么 TrackDBTaskManagerThread 和 TrackTaskManagerThread 这个两个 runnable 都有内置的单线程执行的线程池，是为了什么？

**Comment by dengshiwei** [comment]
`为什么 TrackDBTaskManagerThread 和 TrackTaskManagerThread 这个两个 runnable 都有内置的单线程执行的线程池，是为了什么？`
因为数据采集的过程有time 字段(事件发生时间) 和 _flush_time（刷新上报时间），为了保证事件的时间顺序，所以必须要单线程读取。

**Comment by wangzhzh** [comment]
请问还有其他问题吗？
