### ISSUE TITLE
关于view点击事件绑定Fragment的问题

### ISSUE THREAD

**Issue by Knight-ZXW** [sensorsdata/sa-sdk-android#33]
目前 神策hook了viewCreated事件 为所有的子view添加了tag标识 fragment_name。 
但是这个方案无法解决 view是在viewCreated之后动态添加了（比如recyerlview类控件数据来源于网络，视图会等到网络请求加载完成后才添加）

如何解决这种情况？

目前我的方案是，view点击事件触发时，如果该view 没有 view_fragment_name tag,则在遍历父view的过程中，获取每个父view的 view_fragment_name tag的值，如果发现有，则将该值将作为 点击view的 name_tag

**Comment by dengshiwei** [comment]
针对动态添加的确实会有这个问题，我们内部记录下优化。

**Comment by wangzhzh** [comment]
内部已做讨论，目前会按照您的方案进行开发。
再次感谢您的贡献~

**Comment by Knight-ZXW** [comment]
> 内部已做讨论，目前会按照您的方案进行开发。
> 再次感谢您的贡献~

👌，那我关闭issue了
