### ISSUE TITLE
Android没有trackViewAppClick的方法，iOS有呢。

### ISSUE THREAD

**Issue by hexiangyuan** [sensorsdata/sa-sdk-android#35]

**Comment by wangzhzh** [comment]
该功能正在开发，预计下一个版本会包含此接口。

**Comment by wangzhzh** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/4361619/63951033-a05c4580-caaf-11e9-9f8b-40fc7f9b4d8c.png">

**Comment by hexiangyuan** [comment]
如果我想要手动触发点击事件的参数的话，该用什么方式比较好

**Comment by hexiangyuan** [comment]
/**
         *自定义发送click Json Object事件
         */
        public fun trackJsonObjectString(view: View,jsonString: String) {

            try {
                val jsonObject = JSONObject()
                jsonObject.put("\$properties_ext", jsonString)
                SensorsDataAPI.sharedInstance().setViewProperties(view, jsonObject)
                SensorsDataAutoTrackHelper.trackViewOnClick(view)
            } catch (e: Exception) {
                SALog.printStackTrace(e)
            }
        }


我这样是不是可以手动track click事件呢？

**Comment by dengshiwei** [comment]
`SensorsDataAutoTrackHelper`类是全埋点使用的类，他的 trackViewOnClick 接口是用于处理 View 的点击事件。但是他受到一些全埋点的策略影响，比如如果把 Activity 进行了忽略，就会导致 $AppClick 事件不采集。所以无法完全满足所有手动触发场景的需求。关于手动触发的$AppClick 事件的接口正在开发，预计下一版本会发布该功能。

**Comment by dengshiwei** [comment]
v3.2.6 版本已添加。
