### ISSUE TITLE
SDK gradle中aspectj的配置缺失了？

### ISSUE THREAD

**Issue by wenjianxue** [sensorsdata/sa-sdk-android#6]
在sdk的gradle中只有dependencies.compile引入aspectj，并没有看到其他配置。demo运行起来也没有看到Aspectj的作用。请问是否是gradle中缺失了aspectj的配置？

**Comment by wangzhzh** [comment]
SDK中的demo只是内部使用，很久没有维护了，如果要验证Aspectj，请新建一个project，然后按照官网文档的步骤集成
