### ISSUE TITLE
com.sensorsdata.analytics.android:android-gradle-plugin2插件的主要作用是什么

### ISSUE THREAD

**Issue by zjf920507** [sensorsdata/sa-sdk-android#64]
com.sensorsdata.analytics.android:android-gradle-plugin2插件的主要作用是什么

**Comment by wangzhzh** [comment]
在编译期间通过 ASM 处理 class 文件插入埋点代码，从而达到全埋点的效果。

**Comment by zjf920507** [comment]
谢谢 这个插件可以开源出来吗

**Comment by wangzhzh** [comment]
这不是已经开源了吗？

**Comment by wangzhzh** [comment]
https://github.com/sensorsdata/sa-sdk-android-plugin2
