### ISSUE TITLE
sdk初始化之前应用已经崩溃，捕获不到异常日志

### ISSUE THREAD

**Issue by hhh123hh** [sensorsdata/sa-sdk-android#66]
sdk在application中初始化之前，应用启动时就崩溃，捕获不到异常日志

**Comment by dengshiwei** [comment]
@hhh123hh 你这个有两个意思：
1. SDK 初始化崩溃，你没有抓到异常日志；
2. SDK 没初始化，采集不到 AppCrashed 事件；

如果是 1 的情况，需要你提供详细的异常日志，我们才能分析。如果是 2 的情况是无法处理的，我们的异常采集需要在完成 SDK 的初始化之后并且开启 AppCrashed 采集才能采集。

**Comment by hhh123hh** [comment]
谢谢

**Comment by dengshiwei** [comment]
@hhh123hh 你的问题有进展了吗？

**Comment by hhh123hh** [comment]
这个是应用的bug每次一启动就崩溃，所以不论上面那种情况应该都上传不了日志。即时捕获了也来不及上传的。

**Comment by dengshiwei** [comment]
好的，确认没问题就 OK。
