### ISSUE TITLE
Android6.0的jack编译现在支持了吗？

### ISSUE THREAD

**Issue by CodingZh** [sensorsdata/sa-sdk-android#69]

**Comment by dengshiwei** [comment]
目前是不支持的，`Android` 官方也已不再维护该 `jack` 包编译，采用 `D8`、`R8` 进行工具链编译。详情可参照：https://source.android.com/setup/build/jack
> 警告：自这份 2017 年 3 月 14 日的公告发布之后，Jack 工具链已被弃用。Jack 是 Android 6.0-8.1 的默认 Android 构建工具链。
