### ISSUE TITLE
viewpage2 中fragment 不会执行onHiddenChanged 如何埋点离开

### ISSUE THREAD

**Issue by BaiShou** [sensorsdata/sa-sdk-android#70]

**Comment by dengshiwei** [comment]
目前我们处理 Fragment 的四个方法：onResume、setUserVisibleHint、onHiddenChanged 和 onViewCreated 用于监听页面浏览，对页面离开没有做处理。这块给你的建议通过监听切换相关的监听结合 Fragment 是否可见来尝试解决。
