### ISSUE TITLE
不支持ButterKnife的点击事件了吗

### ISSUE THREAD

**Issue by xubaolin480** [sensorsdata/sa-sdk-android#71]
不支持ButterKnife的点击事件了吗

**Comment by YueJZSensorsData** [comment]
是支持的，我这边用下面的环境测试

在 Butter Knife 的以下版本中

implementation 'com.jakewharton:butterknife:10.2.3'
annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'
classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.3'

使用神策 SDK 版本
implementation 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:4.2.1'

神策插件版本
classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:3.2.6'

并添加神策插件的情况下
apply plugin: 'com.sensorsdata.analytics.android'

能采集到 Butter Knife 的  @OnClick 注解点击事件

**Comment by YueJZSensorsData** [comment]
请求您使用使用神策 SDK 和插件的版本是多少？

**Comment by xubaolin480** [comment]
搞错了，butterKnife支持，我之前排查错了方向
