### ISSUE TITLE
Fragment点击事件自动埋点$title问题

### ISSUE THREAD

**Issue by wpq2014** [sensorsdata/sa-sdk-android#73]
![神策1](https://user-images.githubusercontent.com/6477207/90498856-692ceb80-e17b-11ea-9d63-3f24f16de509.jpg)
![神策2](https://user-images.githubusercontent.com/6477207/90498875-6e8a3600-e17b-11ea-9d46-c815ee998925.jpg)
![神策3](https://user-images.githubusercontent.com/6477207/90498881-7053f980-e17b-11ea-88d4-61bf49d0532f.jpg)

上面截图是点击事件自动埋点的部分代码，我们的Fragment实现了ScreenAutoTracker，实测发现$AppViewScreen事件的$title和$screen_name没问题，但是$AppClick事件的$title和$screen_name是取的Activity的不是当前Fragment的，看源码分析是上面截图2中只处理了Activity没有处理Fragment，所以想确认下是不是这块的问题，如果是希望能加上Fragment的处理，谢谢~~

**Comment by YueJZSensorsData** [comment]
您好，在代码中获取了 fragment 实现 ScreenAutoTracker 的逻辑
 
https://github.com/sensorsdata/sa-sdk-android/blob/0628f03562e7237c86d65f74e0d64d213dc07904/SensorsAnalyticsSDK/src/main/java/com/sensorsdata/analytics/android/sdk/util/AopUtil.java#L690

如果仍然有问题，可断点调试一下，将问题反馈给我们

**Comment by wpq2014** [comment]
@YueJZSensorsData 噢噢 确实！我没看完代码，太粗心了。。谢谢！我调试一下~

**Comment by wpq2014** [comment]
你好！再打扰下，这个问题我已开始描述的不是很清楚，重新整理了一下：
我们有个页面是tab+Fragment，其中一个Fragment是多个Activity会用到的，所以这个Fragment希望能动态设置$title，所以实现了ScreenAutoTracker，但是动态标题是setArguments传递的，具体情况如下：

![神策1](https://user-images.githubusercontent.com/6477207/90621529-6ba84780-e246-11ea-83aa-30018bde06ac.jpg)
![神策2](https://user-images.githubusercontent.com/6477207/90621537-6fd46500-e246-11ea-94de-1426d8bd9d40.jpg)
![神策3](https://user-images.githubusercontent.com/6477207/90621543-719e2880-e246-11ea-8d21-1cd42f31280f.png)
![神策4](https://user-images.githubusercontent.com/6477207/90621549-74008280-e246-11ea-86ad-ec6821fe4762.png)
![神策5](https://user-images.githubusercontent.com/6477207/90621557-75ca4600-e246-11ea-88f6-44ad992b4014.png)

如上，切换到Frg_4，$AppViewScreen事件的$title是当前自定义的没问题，点击RecyclerView第3项$AppClick事件的$title是Activity的，不是当前自定义的，所以想问下这个跟ScreenAutoTracker的调用时机有关还是跟点击事件自动埋点的逻辑有关，点击自动埋点怎么样才能和浏览事件一样动态设置$title，谢谢~~

**Comment by dengshiwei** [comment]
你这边使用的是哪个版本，目前我们的 4.2.2 版本才支持对 RecyclerView 的处理。

**Comment by wpq2014** [comment]
@dengshiwei 我是拉的最新代码测的，不只RecyclerView这样，普通的`tv_frg_4`点击事件标题也是类似问题：

![20200821101600](https://user-images.githubusercontent.com/6477207/90844891-86d69c80-e397-11ea-877e-11c2160e291a.jpg)

页面浏览事件的$title是自定义的没问题，但是点击事件的是Activity的，建议你也试一下这种Fragment动态设置标题的case

**Comment by dengshiwei** [comment]
@wpq2014 我尝试的是可以的。

**Comment by wpq2014** [comment]
直接写死肯定是可以的，但是我的是这种动态传参的情况啊：

![神策3](https://user-images.githubusercontent.com/6477207/90621543-719e2880-e246-11ea-8d21-1cd42f31280f.png)

**Comment by YueJZSensorsData** [comment]
您好，这里利用 ScreenAutoTrack 不生效是因为 SDK 内部是用反射创建 fragment 对象，导致 SDK 内部和实际使用的 fragment 不是同一个对象，类成员变量 title 为空，所以最终采集不对

另外由于 fragment 对象生命周期判断需要几个条件同时判断，所以这种动态设置的场景，目前也不支持自动埋点利用 ScreenAutoTrack 设置，对于这种需求，需要开发者调用 SensorsDataAPI#trackViewScreen(java.lang.String, org.json.JSONObject) 方法触发页面浏览的数据，fragment 上的点击也需要调用 SensorsDataAPI#trackViewAppClick(android.view.View, org.json.JSONObject) 方法采集点击的数据
