### ISSUE TITLE
$AppEnd 中event_duration 字段类型改成Double

### ISSUE THREAD

**Issue by happysdh** [sensorsdata/sa-sdk-android#74]
trackEvent 事件是Double类型
Double duration = Double.valueOf(eventTimer.duration());
if (duration > 0) {
      sendProperties.put("event_duration", duration);
 }
trackAppEnd事件是String类型
properties.put("event_duration", duration(startTime, endTime));

**Comment by YueJZSensorsData** [comment]
您好，非常感谢您发现了这个问题并提供给我们，我们会尽快修复，目前神策后端会有类型转换的功能，不会导致数据不入库

**Comment by YueJZSensorsData** [comment]
最新版已修复
