### ISSUE TITLE
Android端_flush_time字段在H5打通时调用原生会重复

### ISSUE THREAD

**Issue by JianAn-Shi** [sensorsdata/sa-sdk-android#75]
SDK版本：4.4.3
测试机安卓版本：Android 10

问题描述：
App打通H5后通过H5调用原生进行pageView类型的track时，经过断点调试发现上传的json数据中的_flush_time字段重复了，类似于下面所示：
`[{
	"distinct_id": "01bbf41e9c1a0183",
	"lib": {
		"$lib": "js",
		"$lib_method": "code",
		"$lib_version": "1.15.20",
		"$app_version": "2.2.0"
	},
	"properties": {
		.....
	},
	"anonymous_id": "01bbf41e9c1a0183",
	"type": "track",
	"event": "$pageview",
	"time": 1607322079431,
	"_track_id": -665357406,
	"_flush_time": 1607322075401,
	"_hybrid_h5": true,
	"_flush_time": 1607322080377
}]`

**Comment by YueJZSensorsData** [comment]
多谢反馈，此时是原生和 h5 端都添加了 `_flush_time` 字段，导致重复，我们内部确认下影响

**Comment by JianAn-Shi** [comment]
> 多谢反馈，此时是原生和 h5 端都添加了 `_flush_time` 字段，导致重复，我们内部确认下影响

多谢回复，我们公司正在使用你们的产品，现在服务端那边没法解析这个json（涉及到其他部门的逻辑，不好改），麻烦有结果了请告知一声

**Comment by YueJZSensorsData** [comment]
@JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？

**Comment by JianAn-Shi** [comment]
> @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？

服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式

**Comment by YueJZSensorsData** [comment]
> > @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？
> 
> 服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式

您那边是自己的后台解析的嘛，还是神策的后台？

**Comment by JianAn-Shi** [comment]
> > > @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？
> > 
> > 
> > 服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式
> 
> 您那边是自己的后台解析的嘛，还是神策的后台？

是自己的后台，但是内部实现可能不太一样

**Comment by JianAn-Shi** [comment]
> > > > @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？
> > > 
> > > 
> > > 服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式
> > 
> > 
> > 您那边是自己的后台解析的嘛，还是神策的后台？
> 
> 是自己的后台，但是内部实现可能不太一样

我们自己的后台现在没法解析

**Comment by YueJZSensorsData** [comment]
> > > > > @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？
> > > > 
> > > > 
> > > > 服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式
> > > 
> > > 
> > > 您那边是自己的后台解析的嘛，还是神策的后台？
> > 
> > 
> > 是自己的后台，但是内部实现可能不太一样
> 
> 我们自己的后台现在没法解析

嗯嗯，明白，我们这边内部高优先级处理一下，发版后会通知您

**Comment by JianAn-Shi** [comment]
> > > > > > @JianAn-Shi 您好，我这边测试此时 h5 的数据神策服务端是能正常解析的，请问您那边具体的问题是什么，只有原生端，没有 h5 的数据嘛？
> > > > > 
> > > > > 
> > > > > 服务端是先直接入库了，然后用hive解析，但是hive不支持这种类型的json格式
> > > > 
> > > > 
> > > > 您那边是自己的后台解析的嘛，还是神策的后台？
> > > 
> > > 
> > > 是自己的后台，但是内部实现可能不太一样
> > 
> > 
> > 我们自己的后台现在没法解析
> 
> 嗯嗯，明白，我们这边内部高优先级处理一下，发版后会通知您

好的，谢谢了

**Comment by dengshiwei** [comment]
@JianAn-Shi 我们内部已完成优化并发布版本，版本号 v4.4.5

**Comment by JianAn-Shi** [comment]
> @JianAn-Shi 我们内部已完成优化并发布版本，[版本号 v4.4.5](https://github.com/sensorsdata/sa-sdk-android/releases/tag/v4.4.5)

好的
