### ISSUE TITLE
getDeviceInfo优化建议

### ISSUE THREAD

**Issue by William353** [sensorsdata/sa-sdk-android#76]
现在每次上报事件，都需要获取Carrier，IMEI，deviceId，macAddress等，每个方法里都有会判断是否具有网络权限，而网络权限是需要binder通信的，此时会占用binder线程池数量，我的测试手机，小米play（Android8.1.0），网络权限校验执行耗时大概2\~3ms，netWorkType方法大概耗时3\~8ms，整个getDeviceInfo方法大概30ms。
1、获取Carrier，IMEI，deviceId，macAddress等信息的时候，是否可以不判断网络权限？或者只判断一次，所有方法都以参数的形式传入网络权限。
2、Carrier，IMEI，deviceId，macAddress这些值是固定的，是否可以全局保存一份，如果已经有值，就不需要再次获取。

**Comment by dengshiwei** [comment]
@William353 谢谢你的反馈，目前我们已经在做这块的优化了。

**Comment by dengshiwei** [comment]
@William353 我们在 v5.2.2 版本中已经做了优化。
