### ISSUE TITLE
demo 运行失败

### ISSUE THREAD

**Issue by tingtingtina** [sensorsdata/sa-sdk-android#77]
运行 demo 会报以下问题，请帮助

* What went wrong:
Execution failed for task ':demo:transformClassesWithSensorsAnalyticsAutoTrackForDebug'.
 java.io.FileNotFoundException: Android jar not found!

**Comment by dengshiwei** [comment]
@tingtingtina 你检查下工程的 Android  SDK 目录是你本地的目录吗？

**Comment by tingtingtina** [comment]
是本地目录，新建工程中直接依赖 sdk 也有同样的问题

**Comment by dengshiwei** [comment]
@tingtingtina 你这边方便的话把你的 demo 发一下

**Comment by tingtingtina** [comment]
新建的项目 android gradle plugin 是 4.1.0；gradle 是6.5.0 不知道对插件是否有影响
便使用git这个项目跑一下，build 可以通过，运行就遇到下面的问题了。
![image](https://user-images.githubusercontent.com/7575884/108496626-4b387300-72e5-11eb-8177-4faf37406823.png)

**Comment by dengshiwei** [comment]
@tingtingtina 出现这个错误的原因是因为插件编译的时候没有找到对应路径下的 Android SDK，一般是不会有这个问题的。所以想看看你的 demo 这边是怎么配置的。

**Comment by tingtingtina** [comment]
![image](https://user-images.githubusercontent.com/7575884/108498155-6dcb8b80-72e7-11eb-8deb-eb6fd848b9a1.png)

**Comment by dengshiwei** [comment]
@tingtingtina 你这边发一下问题 demo 给我看看吧

**Comment by tingtingtina** [comment]
解决了问题，我的sdk 目录结构是左边的，改成右边的就好了 - - ||，android-30-2 改成了 android-30 就找的到了
![image](https://user-images.githubusercontent.com/7575884/108580730-c6426d80-7367-11eb-8305-d942281a8ab0.png)
