### ISSUE TITLE
com.sensorsdata.analytics.android.sdk.util.AopUtil.buildTitleAndScreenName 方法耗时较高

### ISSUE THREAD

**Issue by William353** [sensorsdata/sa-sdk-android#78]
耗时有点高啊，老铁
主要是每个页面都要执行getActivityTitle
手机：红米k30pro

![Lark20210224-112417](https://user-images.githubusercontent.com/5203512/108943225-5ac40d00-7693-11eb-9833-07578030afd0.png)
![Lark20210224-112810](https://user-images.githubusercontent.com/5203512/108943255-644d7500-7693-11eb-8c56-c6b040488258.jpeg)

**Comment by dengshiwei** [comment]
@William353 因为 SDK 内部是不依赖 support 包，所以对于页面标题的获取采用的是反射进行，反射的方式会有些耗时。

**Comment by William353** [comment]
> @William353 因为 SDK 内部是不依赖 support 包，所以对于页面标题的获取采用的是反射进行，反射的方式会有些耗时。

下面走到了 createSubdecor，创建了布局，主要是这个方法的耗时。获取标题这里能优化下吗，如果没有别的方法的话，是不是可以直接上报activity name ？

**Comment by dengshiwei** [comment]
@William353 SDK 层主要是通过 getSupportActionBar 反射获取 ActionBar 对象，来读取标题。createSubdecor 应该是 Android 系统层进行处理的，为了保证取值的准确性合理，所以才没完全依照 activity name 进行处理。
