### ISSUE TITLE
maven仓库找不到sdk

### ISSUE THREAD

**Issue by liulunsheng** [sensorsdata/sa-sdk-android#79]
Could not find SensorsAnalyticsSDK.jar (com.sensorsdata.analytics.android:SensorsAnalyticsSDK:5.0.1).
      Searched in the following locations:
          http://maven.aliyun.com/repository/jcenter/com/sensorsdata/analytics/android/SensorsAnalyticsSDK/5.0.1/SensorsAnalyticsSDK-5.0.1.jar

**Comment by dengshiwei** [comment]
@liulunsheng 你这边使用的阿里云仓库，阿里云仓库自动同步的进度有所落后，建议你这边使用 Jcenter 或 Maven 仓库
