### ISSUE TITLE
你好，我在AndroidX里调用了fragment的自动监听但是却没有任何反应。我该如何解决以下是配置

### ISSUE THREAD

**Issue by AuroraStarMoon** [sensorsdata/sa-sdk-android#80]
SAConfigOptions saConfigOptions = new SAConfigOptions(PublicData.SA_SERVER_URL);

        saConfigOptions.setAutoTrackEventType(SensorsAnalyticsAutoTrackEventType.APP_CLICK |
                SensorsAnalyticsAutoTrackEventType.APP_START |
                SensorsAnalyticsAutoTrackEventType.APP_END |
                SensorsAnalyticsAutoTrackEventType.APP_VIEW_SCREEN)
                .enableLog(true);
        saConfigOptions.enableVisualizedAutoTrack(true);
        SensorsDataAPI.startWithConfigOptions(this, saConfigOptions)

        // 初始化 SDK 之后，开启自动采集 Fragment 页面浏览事件
        SensorsDataAPI.sharedInstance().trackFragmentAppViewScreen();

**Comment by dengshiwei** [comment]
@AuroraStarMoon 你好，以上代码是正确的。对于 Fragment 的页面浏览事件采集需要集成我们的插件，这里可以参照我们的[插件集成文档](https://manual.sensorsdata.cn/sa/latest/page-1573907.html#id-.AndroidSDKv1.13-%E5%BC%95%E5%85%A5%E6%8F%92%E4%BB%B6)集成插件，然后使用。

**Comment by AuroraStarMoon** [comment]
是我没有注意，以为导入SDK了就没必要导入插件了，打扰了。非常感谢回答。已解决。
