### ISSUE TITLE
getViewNode 优化建议

### ISSUE THREAD

**Issue by Knight-ZXW** [sensorsdata/sa-sdk-android#81]
getViewNode 内部涉及到对View层级向上的遍历及 viewPath字符串的生成， 在布局复杂的情况下 耗时会达到100ms左右。

这一块是否可以在主线程先 生成 view树结构，在子线程做View树结构的解析 及 viewPath的生成 （涉及到大量的字符串拼接)。

**Comment by dengshiwei** [comment]
@Knight-ZXW 谢谢你的建议，我们内部会考虑一下

**Comment by dengshiwei** [comment]
@Knight-ZXW 我们 SDK 在 v6.2.6 版本中针对这块做了优化，感谢你的反馈。
