### ISSUE TITLE
在哪可以看到错误信息

### ISSUE THREAD

**Issue by carterinchina** [sensorsdata/sa-sdk-android#84]
android sdk 埋点数据”courseid“ 和”resourcetype“ 之前还有数据，今天测试无法在后台查询到数据，把这两个字段替换成其他的字段后可以查询到新的字段的数据，

有没有地方可以看到这两个字段为什么出现了异常吗？

**Comment by dengshiwei** [comment]
@carterinchina 这两个命名都是合法的，所以在 SDK 端是无法查看的。建议去后端查看

**Comment by carterinchina** [comment]
有没有后端的联系方式，或客服的联系方式呢？

**Comment by dengshiwei** [comment]
@carterinchina 如果你是我们的客户，你可以在对应的客户群反馈，或者扫码添加到我们开源社区群咨询，![二维码](https://camo.githubusercontent.com/7528f1679e39a22ed75dea52a016310b9105d7bc79265adede481319c795798f/68747470733a2f2f6f70656e736f757263652e73656e736f7273646174612e636e2f77702d636f6e74656e742f75706c6f6164732f436f6e74656e74436f6d6d6f6e5069635f312e706e67)

**Comment by dengshiwei** [comment]
已加群，关闭该问题。
