### ISSUE TITLE
Issue accessing the Maven

### ISSUE THREAD

**Issue by omidheshmatinia** [sensorsdata/sa-sdk-android#86]
Hi, From this morning, we can not access the Maven repository and all the builds fail.

![Screenshot 2021-07-20 at 11 28 55](https://user-images.githubusercontent.com/9485780/126259312-6ef3dd52-6548-48e3-805b-05069d7f64a4.png)

any suggestion on how can we fix this issue?

**Comment by dengshiwei** [comment]
Now jcenter is disabled，add mavenCentral().
![image](https://user-images.githubusercontent.com/12447711/126260085-06de9d41-573b-4eaa-b87a-7e7d9613795d.png)

**Comment by omidheshmatinia** [comment]
thanks for replying so fast. I check again and see we already added mavenCentral. 
should i also remove this part?

`maven {
    url 'https://dl.bintray.com/zouyuhan/maven'
}`

**Comment by dengshiwei** [comment]
Yes, you can
