### ISSUE TITLE
可视化埋点配置是什么结构？

### ISSUE THREAD

**Issue by seaguest** [sensorsdata/sa-sdk-android#87]
最近打算采用神策sdk做一个自己的数据采集平台，目前从代码看主要有2个接口：
1，/config/visualized/Android.conf，获取可视化埋点配置接口
2，数据上报接口，这个事件信息可以从log看到。

但是可视化埋点配置返回的是什么样子就没有数据，能不能提供一下样本呢？

**Comment by dengshiwei** [comment]
@seaguest 
1. 接口的协议目前还无法提供，这个可以根据自己的需求去定义；
2. 数据上报的信息可以通过 log 查看。
