### ISSUE TITLE
全埋点的相关问题

### ISSUE THREAD

**Issue by haibin80s** [sensorsdata/sa-sdk-android#9]
最近看了下神策全埋点的实现，看到fragment访问有些问题请教
1.FragmentAspectj类中onResumeMethod中对JoinPoint执行类的判断，判断fragment是否是android.support.v4.app.Fragment。
由于fragment类名是通过targetMethod.getDeclaringClass().getName()获取的，只能获取执行类的类名，而不能获取继承类的类名，所以这块的代码判断会有问题，继承android.support.v4.app.Fragment的fragment执行onresume时不会执行下去。
既然Pointcut是android.support.v4.app.Fragment.onResume()，那么就不需要对android.support.v4.app.Fragment进行判断了吧？
2.既然利用aspect支持了android.support.v4.app.Fragment访问事件，那么暂不支持android自带的fragment访问的原因是什么？

**Comment by wangzhzh** [comment]
1、我们已经修复，具体可以参考源码
2、原生的 fragment，不同的版本差异比较大，目前还没有比较好的方案处理这种兼容性，而且 App 开发的时候，一般也不会使用自带的 fragment，都会使用 support 里的fragment
