### ISSUE TITLE
客户端数据加密存储

### ISSUE THREAD

**Issue by littlezhuang** [sensorsdata/sa-sdk-android#92]
神策目前的sdk采集的中间结果数据会存在Android app的私有目录，这些信息比较敏感，目前有策略对这些数据进行加密再存储么？

**Comment by dengshiwei** [comment]
@littlezhuang 目前 SDK 还没有策略进行处理，后面会考虑你反馈的加密需求。

**Comment by dengshiwei** [comment]
@littlezhuang SDK 已经在 6.2.0 版本中支持对本地缓存中间数据加密。具体使用方式在初始化时设置秘钥 `configOptions.registerStorePlugin(new SAEncryptStorePlugin(this));`
