### ISSUE TITLE
使用V6.1.0版本，页面切换出现频繁GC，偶发OOM

### ISSUE THREAD

**Issue by chenguangtu** [sensorsdata/sa-sdk-android#93]
使用V6.1.0版本，页面切换出现频繁GC，偶发OOM
日志中会出现大量的错误日志：Invalid ID 0x.......

**Comment by dengshiwei** [comment]
@chenguangtu OOM 这块有日志能提供一下。Invalid ID 的日志是由于你的控件中有 View 的 ID 不合法，我们在查找过程中系统层会出现异常，目前对于 Invalid ID 的判断内部优化中。

**Comment by dengshiwei** [comment]
@chenguangtu SDK 已在 v6.1.1 的版本中进行修复。
![image](https://user-images.githubusercontent.com/12447711/158324099-e6bdcdc2-e757-424a-92af-a93ef86e7796.png)
