### ISSUE TITLE
flush 时间和打点时间间隔较远

### ISSUE THREAD

**Issue by bruce3x** [sensorsdata/sa-sdk-android#94]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/15318754/158149726-6c96282f-12d9-4fde-9602-e34b89a15640.png">

请问一下什么情况下，会导致这个问题？ 有没有解决或者优化的方法？

**Comment by dengshiwei** [comment]
@bruce3x 看截图这个表结构不是我们 SDK 默认的表结构，应该是被你修改过的。你这里最好确认一下你的 recommendTime 和 flush_time 采集入库的时机

**Comment by bruce3x** [comment]
后来我们推荐同学说这个用户是 iOS 的，我先把 issue 关了，尴尬😅 
打扰了
