### ISSUE TITLE
如何动态切换上报地址？

### ISSUE THREAD

**Issue by TianyaHelp** [sensorsdata/sa-sdk-android#97]
android 集成问题
需求如下 ，APP SDK 和 APP 的 统计分开，现在 开发的APP SDK 中集成了 神策，APP 本身也集成了神策，  设想是 动态 设置 上报地址，当进入SDK 页面时，设为SDK 的上报地址，退出SDK 页面时，恢复为APP 本身的 上报地址  发现 上报地址 初始化 后 无法更改，

 SensorsDataAPI.getConfigOptions().setServerUrl("url1");   // 初始化时设置

  SensorsDataAPI.getConfigOptions().setServerUrl("url2");  // 动态设置

未生效

**Comment by dengshiwei** [comment]
@TianyaHelp 你这种写法是不正确的使用，正确使用 SensorsDataAPI.sharedInstance().setServerUrl();

**Comment by TianyaHelp** [comment]
谢谢
