### ISSUE TITLE
是否是键盘view判断会出现误判，导致demo gridview 的点击事件不被采集

### ISSUE THREAD

**Issue by haegyeong** [sensorsdata/sa-sdk-android#99]
KeyboardViewUtil.isKeyboardView(View view) 这个判断有问题

**Comment by dengshiwei** [comment]
@haegyeong 你这边能举一个例子吗？我们当时考虑的是采用一种近似模糊匹配的方式

**Comment by dengshiwei** [comment]
@haegyeong 这个 demo 因为太简单了，所以里面设置的都是数字 1、2、3 这种，所以命中。实际业务场景一般是很少的。

**Comment by haegyeong** [comment]
虽然实际业务场景少，但是这个问题还是存在，就会导致事件的丢失了。[捂脸]

**Comment by dengshiwei** [comment]
这种情况你可以在 build.gradle 中把这个功能关闭。
```xml
    sensorsAnalytics {
        disableTrackKeyboard = true
    }
```
